### ISSUE TITLE
UI : default

### ISSUE THREAD

**Issue by botrote** [botrote/GposWinterPro_tmp#6]
플레이 화면 기본 UI 적용(기획서 14p 참조, 미니맵 제외 할것)

UI 에셋 : http://bitly.kr/dYILVg9p

파일 내 readme 읽은 후 작업 바람

**Comment by chj990707** [comment]
UI 앵커가 화면 중앙을 기준으로 맞춰져 있음. 모서리 기준으로 변경 필요
